- name: play level variable 
  hosts: local
  connection: local
  vars_files:
  - course.yaml


  tasks:
   - name: print variables
     vars:
      COURSE: ansible
     ansible.builtin.debug:
       msg: " course is: {{ COURSE }}, duretion is: {{ DURETION }} "