[mongodb]
mongodb-dev.daws-92s.store

[catalogue]
catalogue-dev.daws-92s.store

[redis]
redis-dev.daws-92s.store

[user]
user-dev.daws-92s.store

[cart]
cart-dev.daws-92s.store
[mysql]
,mysql-dev.daws-92s.store

[payment]
payment-dev.daws-92s.store

[rabbitmq]
rabbitmq-dev.daws-92s.store
[shipping]
shipping-dev.daws-92s.store

[all:vars]
 ansible_user=ec2-user
 ansible_password=DevOps321
 MONGODB_HOST=mongodb-dev.daws-92s.store
 CATALOGUE_HOST=catalogue-dev.daws-92s.store
 REDIS_HOST=redis-dev.daws-92s.store
 USER_HOST=user-dev.daws-92s.store
 CART_HOSTS=cart-dev.daws-92s.store
 MYSQL_HOST=mysql-dev.daws-92s.store
 SHIPPING_HOST=shipping-dev.daws-92s.store
 RABBITMQ_HOST=rabbitmq-dev.daws-92s.store
 PAYMENT_HOST=payment-dev.daws-92s.store

 